### ISSUE TITLE
Could not load file or assembly - Microsoft.AnalysisServices

### ISSUE THREAD

**Issue by orsim25** [marclelijveld/External-Tools-Model-Documentation#22] opened 2022-01-04 20:10 UTC
Hello!

I attempted to start using the new version of the tool this afternoon. I installed using the v2.0.0 msi file. I see the icon in External Tools, but I was met with this error when trying to run the tool: 
![image](https://user-images.githubusercontent.com/62885872/148117816-d7d81940-b17a-42dc-9004-83b6266f42e1.png)

Thank you for your help.

Best,
Matt

**Comment by samaguire** [comment] 2022-01-05 01:33
Same issue ... 😥

![image](https://user-images.githubusercontent.com/62320770/148146565-a3138f8e-4120-4001-b1ea-387164f5ed0a.png)

**Comment by pugliathomas** [comment] 2022-01-05 04:45
Same issue here. Exact same error on two different machines

**Comment by marclelijveld** [comment] 2022-01-05 08:17
Hi @orsim25, @samaguire and @pugliathomas 
I'm sorry you encountered this issue. Can you please go to C:\Power BI Model Documenter and share what is in the log file that you find there? That should tell more about the exact step where it got stuck.

**Comment by marclelijveld** [comment] 2022-01-05 08:36
A quick search for me resulted in a [pretty old item on the SQL Server forum](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/991a0463-92d0-4f38-9594-19233ebbff05/could-not-load-file-or-assembly-quotmicrosoftanalysisservicesquot?WT.mc_id=DP-MVP-5003435&forum=sqlanalysisservices) which explains that it is potentially due to a missing assembly which comes with SSMS for example. So it may be caused by AMO missing. 

Although this NuGet package is part of the Model Documenter tool installation, the assembly could not be found during execution of the tool. On a Windows machine there is something called _Global Assembly_ where all DLL files are located which can be used by local client applications. It seems that the _Microsoft.AnalysisService.dll_ assembly is not there. 

As Power BI runs Analysis Services under the hood, it looks like you're missing the right client libraries to connect to the Analysis Services instance that runs behind Power BI. You can download and install them from the [official MSFT website here](https://docs.microsoft.com/en-us/analysis-services/client-libraries?view=azure-analysis-services-current&WT.mc_id=DP-MVP-5003435#download-the-latest) 

Could you try if this fixes your issue? 
Thanks!

**Comment by samaguire** [comment] 2022-01-05 08:37
> Hi @orsim25, @samaguire and @pugliathomas I'm sorry you encountered this issue. Can you please go to C:\Power BI Model Documenter and share what is in the log file that you find there? That should tell more about the exact step where it got stuck.

Hi @marclelijveld 

For me, the folder doesn't exist.

BTW, I've seen this sort of error before in TE3 (https://github.com/TabularEditor/TabularEditor3/issues/192#issuecomment-924850573). I was referencing the assembly "Microsoft.AnalysisServices.Core.dll" in a C# script to execute a dataset backup command and hitting an error. I found out that TE3 wasn't checking the program's installation directory for the dll files. (Which has now been fixed by Daniel Otykier.) The temporary solution was to specify the full file path, including directory, when loading the assembly. It would seem to be a similar problem here as I can see the assembly is included in the installation dir. Maybe this helps 🤷‍♂️.

Config file attached: [ModelDocumenter.exe.config.txt](https://github.com/marclelijveld/External-Tools-Model-Documentation/files/7813307/ModelDocumenter.exe.config.txt)

**Comment by FilK78** [comment] 2022-01-05 10:18
Hello,

First congratulation for your project : it's gonna be really useful for many users.

I tried the tool this morning. Unfortunately it didn't work. What I could see :
-  I have my shortcut on my ribbon but when I click on the button, it ends very fact
- "C:\Power BI Model Documenter" was not created during installation (or test) =>  I created it manually to check it could fix my issue but It did not fix anything. After a rerun, still no file inside this folder
- No pbit file generated in 'C:\Power BI Model Documenter folder' + no PBIT file generated in "C:\Program Files (x86)\Data-Marc\ModelDocumenter"

- same log as in the pricture above "unhandled exception: system.IO.FileLoadException: Could not load 'or assembly Microsoft.Analysis Services, version ..."


[ModelDocumenter.exe.config.txt](https://github.com/marclelijveld/External-Tools-Model-Documentation/files/7814131/ModelDocumenter.exe.config.txt)

------------------------------
If you want me to test anything, just let me know.

Regards,

Philippe

**Comment by marclelijveld** [comment] 2022-01-05 11:05
@FilK78 Thanks for flagging. We identified the issue and we are working on a fix as we speak.

**Closed as completed** 2022-01-05 11:12 UTC
Labels: Fixed

**Comment by marclelijveld** [comment] 2022-01-05 11:32
Thanks @pugliathomas @samaguire @orsim25 @FilK78 for bringing this up! 
I managed to reproduce on a clean VM. @tonswart helped me to fix the issue directly and we just published v2.0.1 which you can download [here](https://data-marc.com/model-documenter/) In this new version the issue is resolved.

**Comment by orsim25** [comment] 2022-01-05 12:11
Thank you for the help, everyone!

**Comment by samaguire** [comment] 2022-01-05 21:58
> Thanks @pugliathomas @samaguire @orsim25 @FilK78 for bringing this up! I managed to reproduce on a clean VM. @tonswart helped me to fix the issue directly and we just published v2.0.1 which you can download [here](https://data-marc.com/model-documenter/) In this new version the issue is resolved.

Working now. Cheers!

**Comment by FilK78** [comment] 2022-01-05 22:21
Good job. I tested and it works perfectly for me 👍 
1. I downloaded the version 2.01
2. I installed over the older version
3. I tested on a simple file ( my pbix I use for my demo)

It's really useful : entering description for measures /tables now make sense.

Question: I can see you retrieved Power BI description for table and measures but not for columns. Is it a choice ?

Thanks for job, I'm really impressed.

**Comment by marclelijveld** [comment] 2022-01-06 10:50
Thanks for circling back @FilK78, great to hear its working now! 
On the descriptions and columns, it is not a choice... I might have forgotten that. I will list it for future enhancements to also include column descriptions. I created issue #27 to keep this on the radar. 

Thanks for the feedback! Keep it coming :)
